# Generated by Django 3.2.16 on 2022-10-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleNum', models.CharField(max_length=20)),
                ('Vehicletype', models.CharField(max_length=20)),
                ('VehicleModel', models.CharField(max_length=20)),
                ('VehicleDes', models.CharField(max_length=200)),
            ],
        ),
    ]
